
services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
    healthcheck:
      # This command checks if the broker is responding
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  inventory-service:
    build: ./inventory-service
    depends_on:
      kafka:
        condition: service_healthy # --- WAIT FOR HEALTHY, NOT JUST STARTED ---
    environment:
      KAFKA_BROKER: kafka:9092

  # --- BACKEND: ORDER SERVICE (PRODUCER) ---
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5005:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  # --- BACKEND: SSE SERVICE (DISPATCHER) ---
  sse-service:
    build: ./sse-service
    container_name: sse-service
    restart: on-failure
    ports:
      - "5001:5001"
    environment:      # <--- This must be indented 4 spaces
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379
    depends_on:       # <--- This must be indented 4 spaces
      - kafka
      - redis

  # --- FRONTEND: REACT CLIENT ---
  react-app:
    build: ./react-client
    container_name: react-app
    volumes:
      - ./react-client:/app
      - /app/node_modules # This "hides" the container's node_modules from being overwritten by your Mac
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with file watching in Docker